[package]
name = "rs-async-learn"
version = "0.1.0"
edition = "2021"

[workspace]
members = [ "."
    , "build-event-loop-001"
    , "ch01"
    , "ch03"
    , "ch04-epoll"
    , "delayserver"
]

[dependencies]
